POST http://localhost:9000/notes
Content-Type: application/json

{
    "title": "go the gym",
    "description": "go the gym today and train shoulders",
    "priority": 1,
    "dateTime": "2025-01-01"
}